### ISSUE TITLE
Problem with registration

### ISSUE THREAD

**Issue by L3GEND-IQ** [M1TKO/my-note-webapp#3]
hello

thank you for this script

i have download this script and install it on my website

and do it every thing to make it work good

but when i enter page to register and complete information , user not registered in database!

is there is any fix ?

url : http://hack-one.com/save-passwords-online/

and thank you <3

all recpect to you from iraq

**Comment by M1TKO** [comment]
Hello,
thank you for your feedback. 
I think that I can fix it as soon as posible.

**Comment by L3GEND-IQ** [comment]
hello , thank you for replay

ok i will wait 👍

**Comment by M1TKO** [comment]
_Hello friend,_
 I think that I fixed the issue.
The problem was in the **my_note.sql** file. It didn't contained all queries that are needed for the fully functional app.
Now you just import the **my_note.sql** to your phpMyAdmin or whatever you are using and you are ready to go. 

_(if you have a problem just download the latest version of the repo and if should work)_
